# -*- coding: utf-8 -*-
"""accuracy_func.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XZBOh581XY-1LkUcq_PFKpEm2rQZvq1U
"""

def accuracy(label):
  c = 0
  for i in range(len(label)):
    if label[i] == 0:
      c = c + 1
  print(c/ len(label))