# -*- coding: utf-8 -*-
"""Unigram_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XZBOh581XY-1LkUcq_PFKpEm2rQZvq1U
"""

def Unigram_model(temp, dic, zerogram):
  P = 1
  N = sum(dic.values())
  for i in range(len(temp)):
    if temp[i] in dic.keys():
      Pwi = dic[a[i]] / N
    else:
      Pwi = zerogram
    P = P * Pwi
  return P